version: "3.8"
services:
  frontend:
    build:
      context: . # Carpeta principal donde está tu Dockerfile
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src # Aquí aseguras que la carpeta src se mapea correctamente en el contenedor
      - /app/node_modules # Esto evita conflictos con los módulos dentro del contenedor
    depends_on:
      - backend
    networks:
      - mynetwork
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "512M"

  backend:
    build:
      context: . # Usa el mismo Dockerfile para frontend y backend
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=elmensual_transacciones
      - DB_USERNAME=root
      - DB_PASSWORD=password
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    depends_on:
      - db
    networks:
      - mynetwork
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "512M"

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: elmensual
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynetwork

volumes:
  db_data:

networks:
  mynetwork:
    driver: bridge
